name: wakoo_app
description: "Wakoo - Application immobilière avec construction 3D"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_unity_widget: ^2022.2.0
  rive: ^0.12.4
  lottie: ^2.7.0
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/unity/
